version = 1

[[annotations]]
path = ["CMakeLists.txt", "live555.pc.in", "live555Config.cmake.in", "package.xml", "README.md", "CHANGELOG.rst"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025, Timo Röhling"
SPDX-License-Identifier = "BSD-1-Clause"

[[annotations]]
path = ["live555/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "1996-2025, Live Networks, Inc"
SPDX-License-Identifier = "LGPL-3.0-or-later"
